linters:
  enable:
    - gofmt
    - gocyclo
    - bidichk
    - decorder
    - dupword
    - errname
    - errorlint
    - godot
    - gosec
    - makezero
    - misspell
    - nilnil
    - noctx
    - bodyclose
    - prealloc
    - predeclared
    - stylecheck
    - tenv
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G501 # excluded md5 usage error, because it is used only for non-vulnerable hashes for simplicity
      - G401 # same as above
output:
  format: colored-line-number
  print-issued-lines: false
  print-linter-name: true