name: Unit tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  unit_test_go:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Get dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...
        