name: Unit tests and coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  unit_test_go:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5

      - name: Get dependencies
        run: go mod download

      - name: Run unit tests with coverage
        run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
